### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Duchey101** [ginsm/forgotten-graves#102]
**Describe the bug**
Admins can't destroy graves

**Forgotten Graves Version**
3.2.10+1.20.1.jar

**To Reproduce**
A list of steps to reproduce your issue, i.e.:
1. Retrieval type to "USE", droptype to "EQUIP". set graverobbing to false and OPOverrideLevel to whatever level your OPs have
2. Place an unmarked grave in creative or have one spawn by retrieval bugging out (non-reproducible so far happens randomly)
3. Attempt to destroy grave as admin like you would any other block, no dice.
4. Attempt to remove grave through setblock minecraft:air, this will also error out and do nothing.
5. Attempt to use graves list command to find the grave, however it has no player attached so it doesn't show up anywhere.

**Expected behavior**
Grave would be destroyed/removed once an admin of sufficient level comes over and breaks the grave block.

**Additional context**
This has become a big issue on our server as unmarked graves are popping up since there's a bug with the retrieval system sometimes not removing the grave and simply removing the playerdata related to it. this makes it impossible to remove the grave through commands or physically whilst it still takes up a block.

**Screenshots**
![image](https://github.com/user-attachments/assets/385a622d-6cd9-4233-bc0a-e846f513d4df)
row of bugged graves, completely indestructible. I should build a fort out of these.

**Comment by ginsm** [comment]
Thanks for the report!

I had made graves [more resilient to non-player removal](https://github.com/ginsm/forgotten-graves/commit/a22c65f490f1a237f317076d23d3264301cf0f7d) in `3.2.10` in hope that it'd prevent more mods from removing graves unintentionally. It's a very aggressive approach, though, and pretty much makes it so that unless the mod itself removes the grave.. nothing should be able to. I'll make sure to add a config option to toggle that functionality soon.

However, the fact that you can't break graves with no owners when the retrieval type is set to `USE` is definitely unintentional. I'll try and get that bug fixed later today and an update pushed out.

> have one spawn by retrieval bugging out (non-reproducible so far happens randomly)

If this occurs again, can you try and post any client/server logs from when it happened? :thinking: I haven't had it happen yet personally but maybe it's a conflicting mod?

**Comment by ginsm** [comment]
I did figure out what was making unowned graves indestructible with that configuration and it'll be fixed in `3.2.13`. I gotta test some other code I'm adding in the update and if it's all good then I'll push the update out.

Nothing pops out *too* much from the modpack.. but if I had to guess, maybe something to do with one of the Origins? I have heard that Soulslike Weaponry is brutal on grave mods as well but haven't gotten around to actually testing it. It's still breaking graves even after the aggressive approach at preventing mods from doing so? :thinking:

**Comment by Duchey101** [comment]
nah the bosses are not breaking them, I would've had complaints about people losing items and I haven't had any yet (one exception, but that wasn't a bug, just a skill issue from the player in question) if this was the case.
Though to be fair the player that acquired the graves told me that he thinks he got them during the bossfight, so god knows if soulslike is even related to the problem. It's been causing other problems on the server though so I might've been a bit biased to point a finger at it immediately, my bad.

**Comment by ginsm** [comment]
Gotcha, that's good, I'm glad to hear nobody's losing items or anything. So when the retrieval bug happens, the player gets their items back and everything, the grave just doesn't disappear?

I just finished up testing btw and everything seems good. I went ahead and made it so that `/setblock` works on graves too regardless of whether they're owned or not. Pushing out the update now, it should be on CurseForge and Modrinth in like 15-20~ minutes or so.

**Comment by Duchey101** [comment]
ight sick, will pushing to the serverside apply the patch or do clients need to update also?

**Comment by ginsm** [comment]
Hmm, a lot has changed between `3.2.10` and `3.2.13`.. I'd recommend updating it on the server + client just to be safe.

**Comment by ginsm** [comment]
I'm going to go ahead and close this since it should be fixed now. If you have any more issues feel free to open another issue. Thanks again for the report!
