### ISSUE TITLE
[BUG] Grave replacing torches

### ISSUE THREAD

**Issue by marlester-dev** [ginsm/forgotten-graves#106]
**Describe the bug**
When I place a torch and die in it, the torch is getting replaced by the grave.

**Forgotten Graves Version**
v3.2.15+1.20.1

**To Reproduce**
A list of steps to reproduce your issue, i.e.:
1. Download Forgotten Graves v3.2.15+1.20.1 and Fabric 0.16.9
2. Die in a torch
3. The torch is being replaced by a grave.

**Expected behavior**
The grave is not replacing the torch

**Comment by ginsm** [comment]
Thanks for the report! I'm going to remove torches from being replaced for the next version, but it's currently customizable via a datapack using the `replaceable` tag found [here](https://github.com/ginsm/forgotten-graves/tree/main/versions/1.20.1/src/main/generated/data/forgottengraves/tags/blocks).

**Comment by ginsm** [comment]
Awesome! I'm going to close this issue since the fix has been added in the development branch already. I'll also be adding a config option to disable the functionality altogether (#108). And I ended up realizing that the `do_not_replace` tag isn't respected when the block is found within the `replaceable` tag as well (I was going to say add torches to that tag) so I've went ahead and fixed that as well (#107).
