### ISSUE TITLE
[BUG] Can't pickup graves in nether if you're not OP 

### ISSUE THREAD

**Issue by Zaj4c** [ginsm/forgotten-graves#28]
**Describe the bug**
If you die in nether you can not pickup your grave without OP permissions.

**Forgotten Graves Version**
The version is forgottengraves-v2.2.1-mc1.18.1

**To Reproduce**
1. deop your self
2. die in nether
3. now you are not able to pick up your grave
**edit**
also
sometimes you can pick it up only once or twice, if you die again you wont be able to pick it up, in nether ofc

**Comment by ginsm** [comment]
Thanks for the report, looking into it now

**Comment by ginsm** [comment]
Well, that double commit wasn't intentional haha. Either way, this should be fixed in `v2.1.1-mc1.18` and `v2.2.2-mc1.18.1`.

> sometimes you can pick it up only once or twice, if you die again you wont be able to pick it up, in nether ofc

Hmm, admittedly I had only tested this after the fix and it doesn't seem to be occurring for me. Can you test it out on your end and see if it's still happening?

What I tried:

1. Went to the nether 6 times
2. Typed `/kill` each time
3. Attempted to do a mix of breaking and using the 6 graves
4. Repeated step 1-3 with just breaking & just using the graves

Seemed to work for me -- but using the grave does require you to have an empty hand, could that have been the issue?

**Comment by Zaj4c** [comment]
Tested, I think it works, no issues so far, Thanks!
