### ISSUE TITLE
[BUG] Incompatability with Requiem + Origin's "Wandering Soul" Origin

### ISSUE THREAD

**Issue by Limelightbruh** [ginsm/forgotten-graves#39]
**Describe the bug**
Game spawns an empty grave every time you dissociate

**Forgotten Graves Version**
1.2.1
**To Reproduce** (easiest way)

1. Origins and Requiem must be installed.
2. Select the "Demon" soul type and the "Wandering Spirit" Origin (name is a buggy mess but shouldn't be hard to miss)
3. Posses an entity
4. Dissociate from that entity
5. A grave will spawn and death coords will be sent, it seems that the game thinks you die each time you dissociate.

**Expected behavior**
No gravestone should spawn and no death coords should be sent in chat

**Additional context**
This happens when having the "Penance" debuff applied, as Penance forcefully dissociates the player, even when not playing as a wandering spirit. The issue can also be replicated as another origin, as it happens whenever the player dissociates.

**Screenshots**
Unable to use screenshots as this is a problem that must be witnessed in it's entirety.

**Comment by ginsm** [comment]
Hey there,

I've never played around with Requiem or Origins before. I looked into it briefly but I wanted to know what typically happens when you dissociate from a given entity? Do they die or just return to their uncontrolled state?

I have a hunch as to why this might be happening but I'm not quite sure when I can get around to testing/implementing compatibility. I'll try to set aside some time either this weekend or the following weekend to resolve this.

Thanks for the report!

**Comment by Simsz** [comment]
Hi, not sure why the original posted didn't reply to you but... When you disassociate from an entity you are leaving their "body" but you aren't actually dead. That being said, it's hard to fully explain the feature without just trying it out. I'm currently using this mod + requiem and it works mostly okay but the problem arises when: You take over a mob, die as the mob and then your stuff just pops out and doesn't get saved to the grave.

**Comment by ginsm** [comment]
Fixed in 154bce0.
