### ISSUE TITLE
Trinkets "drop_rule" incompatiability

### ISSUE THREAD

**Issue by CatgirlChilis** [ginsm/forgotten-graves#54]
**Describe the bug**
This mod seems to ignore the drop rule flag of trinkets slots;
I made a datapack that sets drop_rule for all trinkets slots to "keep", and without this mod, trinkets placed in those slots remain there across death as expected, but with this mod installed, they're removed from my inventory and added to the grave instead.

**Forgotten Graves Version**
3.0.2 for 1.19.2

**To Reproduce**
1. Create a datapack adding "drop_rule": "keep" to the json file for a trinket slot
2. try dying with a trinket in that slot, both with and without the gravestones turned on in the config

**Expected behavior**
Trinkets in "keep" slots should be left in the players inventory and not added to the gravestone

**Additional context**
Minecraft 1.19.2 with Quilt loader 0.17.11

Edit: Github skipped the issue template screen, my apologies if this is missing a label it would have had if I'd realized

**Comment by ginsm** [comment]
I'll see if I can't throw in a config option for this over the next couple days. Is there a particular version you're using?

**Comment by CatgirlChilis** [comment]
Updated to use the template (github skipped the screen)
quilt 0.17.11, as I added above

**Comment by ginsm** [comment]
Awesome, thanks for the update :)

**Comment by ginsm** [comment]
I made some headway on this.. only trinket slots with their `drop_rule` set to `default` will be handled by this mod after the next update. This means that `keep`, `drop`, and `destroy` will function as intended when set using Trinket's `drop_rule` (as it should be). 

Thanks for bringing this to my attention -- it's something I wouldn't have thought of otherwise. I'll be releasing the update sometime today.
