### ISSUE TITLE
[FEATURE, 1.18.2 pref] Gravestone Spawn Command

### ISSUE THREAD

**Issue by ConqAra** [ginsm/forgotten-graves#76]
gravestones should keep data, so if they are destroyed somehow a /gravespawn command could spawn a gravestone where you're at. even though the grave seem invincible, issues like [https://github.com/miyo6032/bosses-of-mass-destruction/issues/106](https://github.com/miyo6032/bosses-of-mass-destruction/issues/106) can occur. A simple fix would be to add an OP command that is able to spawn your (or any player's, based on @,)" last gravestone with the exact data it held. So that "accidents" can be nullified. When dying, old data is wiped and replaced with new. Is implementing this feature possible?

**Comment by ginsm** [comment]
Hmm, so 1.19.2+ already has backup functionality (with commands to restore/recover graves, delete them, etc).

There's been a lot of refactors and additions since 1.18.2.. so it might be easier to just backport from 1.19.2 to that version. 🤔

I'm not sure when I'll get around to doing so, I've been quite busy lately, but I'll poke around and see. It might be easy enough.

**Comment by ginsm** [comment]
**Update**: I've backported the functionality to 1.19.1 and 1.19 (not released yet).. I'll see if I can't get it backported to 1.18.2 this weekend and release all 3 versions.

**Comment by ginsm** [comment]
OK, I just published this to CurseForge and Modrinth. All of the typical testing I do has been done and it seems fully functional. If you run into any issues, please let me know, thanks!
